### PR TITLE
Remove cilium network policies as they will be installed by the cilium app

### PR DESCRIPTION
**Pull request by fiunchinho**
The cilium app can install the network policies by itself, no need to install them separately.
When upgrading this app, we just need to pass the parameter in the cilium app to make it create the network policies.

### CODE REVIEW

**Comment by fiunchinho** [comment]
Feel free to merge when you feel ready to use the cilium app to create the network policies and follow the same approach on all providers.

**Comment by kopiczko** [comment]
Doesn't that mean that the traffic allowed by those policies will be blocked till the `cilium-app` "takes over"? Don't they have conflicting names in both charts?

**Comment by pipo02mix** [comment]
is this still valid?

**Comment by kopiczko** [comment]
Yeah it is, see https://github.com/giantswarm/giantswarm/issues/22050. But it's ok to close this PR, we can easily recreate it.

**Pull request closed without merging**
