### PR TITLE
remove coredns netpol

### PR DESCRIPTION
**Pull request by bavarianbidi**
As coredns got applied for new clusters via the AppPlatform and we are doing the adoption of all coredns-components via the cluster-shared app we don't need netpol/coredns managed via cluster-resources-app anymore.

**Don't merge: this PR got merged and released after all Clusters got updated**

This PR:

- adds/changes/removes etc

### Testing

Description on how cluster-resources can be tested.

- [ ] fresh install works
  - [ ] AWS
  - [ ] Azure
  - [ ] KVM
- [ ] upgrade from previous version works
  - [ ] AWS
  - [ ] Azure
  - [ ] KVM

#### Other testing

Description of features to additionally test for cluster-resources installations.

- [ ] check reconciliation of existing resources after upgrading
- [ ] X still works after upgrade
- [ ] Y is installed correctly

### Checklist

- [ ] Update changelog in CHANGELOG.md.
- [ ] Make sure `values.yaml` and `values.schema.json` are valid.

### CODE REVIEW

**Review by pipo02mix — APPROVED** [review]
LGTM

**Comment by erkanerol** [comment]
I thought it may be dangerous to delete this directly since there may be incompatibilities in consumers' side.  Therefore, it might be better to add a parameter to disable this manifest and keep rendering it by default. 

Then I checked `default-apps-aws` and `default-apps-gcp`. This app is not used there. Interesting. 

@bavarianbidi @giantswarm/team-hydra Do you know why?

**Comment by bavarianbidi** [comment]
> I thought it may be dangerous to delete this directly since there may be incompatibilities in consumers' side. Therefore, it might be better to add a parameter to disable this manifest and keep rendering it by default.

I'm currently implementing something to keep `coredns` up and running during the adoption phase for existing clusters.
The biggest issue i currently have with the coredns App is the fact, that this app use total different label selectors but most of the k8s object names keep the same (expect the service object itself). And the difference from a `kubadm` orchestrated `coredns` differs a lot from the `coredns` we get via our app platform :disappointed:

**Comment by bavarianbidi** [comment]
> Then I checked `default-apps-aws` and `default-apps-gcp`. This app is not used there. Interesting.
> 
> @bavarianbidi @giantswarm/team-hydra Do you know why?

on `gcp` (and i guess same for `aws`) the `coredns`-App was used from the beginning and this app is shipped with their own network policy.
The `netpol/coredns` in this repo is matching on coredns-pods, shipped by `kubeadm` where the label selector is different.

**Comment by AverageMarcus** [comment]
We don't use this repo in Hydra. Instead we have all this included in `cluster-shared` that's a dep of out cluster charts.

**Comment by pipo02mix** [comment]
is now the case?

**Comment by bavarianbidi** [comment]
> is now the case?

not yet :-( as our MCs aren't updated to the lastest cluster-release yet.

**Comment by bavarianbidi** [comment]
will close the PR as we don't have to take care of these clusters.

**Pull request closed without merging**
