### PR TITLE
Remove coredns network policy

### PR DESCRIPTION
**Pull request by fiunchinho**
As agreed during the kaas sync, the `coredns` resources will be managed by the `ClusterResourceSet` created by the CAPI releases on the different providers. This `coredns` network policy needs to be moved there.

The CAPI releases for the different providers need to add [the `ClusterResourceSet` for the bootstrap process](https://github.com/giantswarm/cluster-gcp/pull/6) and make things optional as needed.

### CODE REVIEW

**Review by whites11 — APPROVED** [review]

**Review by AverageMarcus — APPROVED** [review]
👍

**Comment by kopiczko** [comment]
I won't block that, but that's questionable choice. Why doing it when it works fine?

**Comment by AverageMarcus** [comment]
We install the https://github.com/giantswarm/coredns-app/ chart, which already includes this Network Policy leading to conflicts between the two.

**Comment by kopiczko** [comment]
How do you install it? We don't install it in CAPO

**Comment by AverageMarcus** [comment]
As part of the default apps - https://github.com/giantswarm/default-apps-gcp/blob/4fd0ef9b81cca7d16ce2b842262a41dd1b44f967/helm/default-apps-gcp/values.yaml#L35-L44

**Comment by kopiczko** [comment]
Then we need to also add it here https://github.com/giantswarm/default-apps-openstack/blob/main/helm/default-apps-openstack/values.yaml

**Comment by kopiczko** [comment]
Do you feel comfortable with adopting coredns created by kubeadm?

**Comment by AverageMarcus** [comment]
You also need to ClusterResourceSet in place as Jose said (https://github.com/giantswarm/cluster-gcp/pull/6)

Yeah, we're basically overwriting the default coredns with our own so we use configuration we're happy with.

**Comment by AverageMarcus** [comment]
Also, something to be aware of - our coredns by default expects a different service network CIDR than the kubeadm default (see https://github.com/giantswarm/cluster-gcp/pull/6/files#diff-17e0675d28c6e26ccedf1f4e10e5aa6566aeae8253787d35f8ec89a3a1a52806R36)

**Review by ericgraf — CHANGES_REQUESTED** [review]
This will break CAPO/OpenStack. This is still required.

**Comment by AverageMarcus** [comment]
@ericgraf You're pinning the version to use though aren't you?

Are you not going to be updating the CAPO cluster app to be able to make use of our coredns app?

**Comment by kopiczko** [comment]
We had a discussion in the team about that. We surely would like two things:

- Be aligned.
- Not adopt coredns created by kubeadm. If anything we should disable coredns creation in kubeadm. Or make the app only inject the Corefile.

**Comment by AverageMarcus** [comment]
> * Be aligned.

100% agree

> * Not adopt coredns created by kubeadm. 

We're not exactly, we're replacing it but first we need to make it so it doesn't conflict.

> If anything we should disable coredns creation in kubeadm. 

Not currently possible until a new release of CAPI is out.

> Or make the app only inject the Corefile.

This would still require some level of "adoption" to avoid the conflicts. It will also make upgrades much trickier for our existing customers when upgrading to CAPI clusters because the Corefile they currently have wont be compatible with the one kubeadm deploys without some intervention (a different port number is used).

**Review by ericgraf — APPROVED** [review]
I voiced any concerns I may have .

**Comment by fiunchinho** [comment]
I'm closing this PR in favour of https://github.com/giantswarm/cilium-app/pull/13. We won't use the `cluster-resources-app` on cloud installations, and the required policies will be installed by the cilium app itself. This is optional, so you can continue using `cluster-resources-app` normally, and opt-in to the policies inside the cilium app when it's more convenient for you.

**Pull request closed without merging**
